create table avtopark (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	haydovchi VARCHAR(50) NOT NULL,
	daromad NUMERIC(10,2) NOT NULL,
	moshina_nomi VARCHAR(50) NOT NULL,
	model VARCHAR(50) NOT NULL,
	moshin_yili NUMERIC(4) NOT NULL,
	mashina_raqami NUMERIC(3) NOT NULL,
	moshina_rangi VARCHAR(10) NOT NULL
);
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Elyn Collaton', '55.43', 'Mitsubishi', 'Mirage', 1986, 323, 'Khaki');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('May Cathie', '43.14', 'Infiniti', 'I', 2001, 557, 'Goldenrod');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Marga Ambrosetti', '65.41', 'Acura', 'RL', 2012, 330, 'Blue');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Theodosia Gotts', '69.78', 'Audi', 'S4', 2002, 446, 'Yellow');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Lib Jacobs', '83.11', 'GMC', 'Envoy XL', 2002, 555, 'Goldenrod');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Norri Covell', '43.36', 'Toyota', 'Avalon', 1998, 372, 'Teal');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Dani Creek', '98.54', 'Chevrolet', 'Silverado 2500', 2011, 801, 'Crimson');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Leontyne Rudolph', '74.54', 'Nissan', 'Pathfinder', 2004, 807, 'Goldenrod');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Galina Bonifas', '67.82', 'GMC', 'Savana 3500', 2000, 257, 'Maroon');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Idelle Phillipson', '43.02', 'Ford', 'Escape', 2009, 852, 'Green');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Carie Litton', '97.75', 'Chevrolet', 'HHR', 2007, 831, 'Yellow');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Terese Blaby', '69.62', 'Ford', 'F150', 2007, 741, 'Maroon');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Hillier Galero', '47.09', 'Volvo', 'XC90', 2010, 812, 'Orange');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Rozalie Prester', '98.28', 'GMC', 'Sierra 3500', 2012, 850, 'Orange');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Velma Flatt', '55.14', 'Buick', 'Enclave', 2011, 657, 'Violet');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Daphne McKibbin', '87.56', 'Hyundai', 'Tiburon', 1997, 650, 'Turquoise');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Avigdor Nucator', '67.69', 'Mitsubishi', 'Montero', 1999, 351, 'Turquoise');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Rossie Pickhaver', '40.00', 'Nissan', 'Pathfinder', 2007, 941, 'Orange');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Susannah Ellacombe', '78.92', 'Mazda', 'MX-3', 1996, 524, 'Purple');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Cookie Matieu', '67.61', 'Mitsubishi', 'Galant', 2007, 944, 'Green');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Silvester Srawley', '48.20', 'MINI', 'Cooper Clubman', 2008, 366, 'Teal');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Kalie Yakebovitch', '46.06', 'Ford', 'Econoline E350', 2000, 223, 'Crimson');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Kirsteni Denge', '55.78', 'Subaru', 'Legacy', 2003, 519, 'Aquamarine');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Charles Solano', '96.41', 'Smart', 'Fortwo', 2009, 254, 'Indigo');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Kata Berkery', '82.25', 'BMW', 'X6 M', 2013, 518, 'Goldenrod');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Elberta Lintin', '95.87', 'Oldsmobile', '88', 1993, 240, 'Mauv');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Mady Coatman', '88.83', 'Pontiac', 'Bonneville', 1964, 403, 'Teal');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Jaine Jesty', '65.30', 'Mazda', 'Miata MX-5', 2000, 210, 'Indigo');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Arlyne Cumo', '83.66', 'Audi', '90', 1990, 528, 'Yellow');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Kerianne Guyon', '79.11', 'Lincoln', 'Town Car', 1991, 921, 'Aquamarine');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Cassey Loveless', '72.79', 'Hyundai', 'Excel', 1992, 194, 'Goldenrod');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Lucie Birtles', '77.27', 'Pontiac', 'LeMans', 1964, 602, 'Crimson');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Berget Gravet', '41.01', 'Chevrolet', 'G-Series G30', 1994, 143, 'Maroon');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Silvie McFie', '99.45', 'Acura', 'MDX', 2011, 383, 'Violet');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Leoine Bisco', '45.70', 'Dodge', 'Aries', 1981, 217, 'Pink');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Ernesta Davidovicz', '83.99', 'Mercedes-Benz', 'G-Class', 2004, 822, 'Goldenrod');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Ced Cuberley', '72.86', 'Chevrolet', 'Cavalier', 2005, 517, 'Violet');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Cathi Sargerson', '88.66', 'Chevrolet', 'Tracker', 2004, 378, 'Purple');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Kain Durnall', '53.42', 'Suzuki', 'Grand Vitara', 2003, 135, 'Aquamarine');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Ari Peabody', '65.46', 'Oldsmobile', 'Bravada', 2001, 981, 'Khaki');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Rutherford Lardnar', '62.65', 'Lincoln', 'Continental Mark VII', 1990, 953, 'Crimson');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Currey Tumielli', '68.05', 'Dodge', 'Dakota Club', 1994, 196, 'Orange');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Christos Friese', '86.60', 'Toyota', 'Tundra', 2003, 803, 'Aquamarine');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Kathye Compson', '67.61', 'Hyundai', 'Accent', 2001, 291, 'Aquamarine');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Vivien Gallehawk', '40.21', 'Toyota', 'MR2', 2002, 959, 'Blue');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Jackqueline Iacovazzi', '91.42', 'Chevrolet', 'Venture', 1999, 878, 'Turquoise');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Allyson Rummings', '45.15', 'Pontiac', 'Sunfire', 1998, 727, 'Khaki');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Gabby Ivanchov', '74.51', 'Toyota', 'Solara', 2004, 954, 'Teal');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Agata Drummond', '90.65', 'Ford', 'Bronco II', 1990, 951, 'Teal');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Perl Verty', '69.07', 'Buick', 'Reatta', 1991, 504, 'Turquoise');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Stevy Belmont', '98.84', 'Pontiac', 'Grand Prix', 1990, 240, 'Yellow');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Katharine McNeely', '54.60', 'Toyota', 'MR2', 1985, 519, 'Goldenrod');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Sonia Keddey', '72.65', 'Ford', 'Crown Victoria', 2008, 141, 'Aquamarine');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Wes Adriaens', '90.86', 'Saab', '900', 1993, 121, 'Goldenrod');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Bernadene Leithgoe', '89.61', 'Jaguar', 'XK Series', 1997, 451, 'Fuscia');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Ashlee Malone', '68.62', 'Toyota', 'Corolla', 2002, 567, 'Violet');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Ernest Monketon', '49.03', 'GMC', 'Yukon XL 1500', 2010, 522, 'Purple');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Geri Farmiloe', '74.25', 'Nissan', '350Z', 2008, 878, 'Indigo');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Michelle Fettis', '47.78', 'Lexus', 'GX', 2010, 761, 'Crimson');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Nobie Ogilvy', '55.46', 'GMC', 'Yukon XL 2500', 2001, 685, 'Turquoise');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Sherry Whissell', '88.36', 'Nissan', 'Altima', 2002, 159, 'Indigo');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Diana Linner', '64.04', 'Nissan', '370Z', 2010, 212, 'Teal');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Frannie Batterham', '67.83', 'BMW', '525', 2002, 161, 'Maroon');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Parker Shillabeer', '56.46', 'GMC', 'Envoy', 2008, 349, 'Pink');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Ferd Adamec', '68.82', 'Volkswagen', 'Touareg 2', 2008, 524, 'Fuscia');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Bliss Chevis', '69.70', 'Chevrolet', 'Blazer', 1999, 795, 'Pink');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Tyson Ebbitt', '96.51', 'Chevrolet', 'Suburban 2500', 2003, 227, 'Aquamarine');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Perceval Hanster', '51.22', 'Lexus', 'IS F', 2008, 367, 'Blue');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Leontyne Casetta', '85.33', 'Volvo', '240', 1993, 632, 'Crimson');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Leoine Spieck', '70.97', 'BMW', '7 Series', 2000, 655, 'Blue');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Maude Denyukin', '95.27', 'Buick', 'LaCrosse', 2011, 399, 'Teal');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Bert Prowse', '99.13', 'Kia', 'Optima', 2003, 547, 'Violet');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Janek Mallison', '82.09', 'Subaru', 'Impreza', 2011, 983, 'Fuscia');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Powell Tague', '71.00', 'Mercury', 'Sable', 1993, 557, 'Turquoise');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Elfrida Devonish', '58.91', 'Chevrolet', 'Suburban 1500', 2009, 563, 'Khaki');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Scotty Cramer', '71.66', 'Dodge', 'Dynasty', 1993, 667, 'Yellow');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Cati Umbert', '88.14', 'Porsche', '928', 1990, 754, 'Yellow');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Ellissa Ferriday', '41.11', 'Dodge', 'Ram 3500', 2008, 838, 'Aquamarine');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Nanon Kibel', '44.65', 'Mercury', 'Sable', 1990, 277, 'Blue');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Ilise Denisyev', '76.89', 'Ford', 'Freestyle', 2006, 654, 'Red');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Holden Busswell', '58.99', 'Mazda', 'B-Series', 1991, 680, 'Khaki');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Monro Bagnall', '91.00', 'Hummer', 'H1', 1999, 756, 'Teal');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Laetitia Mycock', '89.08', 'BMW', '8 Series', 1993, 628, 'Fuscia');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Oswell Pierson', '69.01', 'Maybach', '57', 2011, 576, 'Yellow');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Petronilla Crosgrove', '70.76', 'Ford', 'Explorer', 2012, 806, 'Crimson');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Lemmie Yeandel', '82.11', 'Chevrolet', 'Equinox', 2010, 995, 'Khaki');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Risa Heaseman', '92.61', 'BMW', 'X3', 2007, 880, 'Indigo');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Darlene Fairfull', '93.77', 'Audi', 'S5', 2012, 464, 'Violet');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Lyndy Perillo', '96.72', 'Dodge', 'Avenger', 2012, 429, 'Green');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Allx Moggie', '69.34', 'Acura', 'MDX', 2002, 220, 'Maroon');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Renate Lucia', '95.70', 'Chrysler', 'Town & Country', 1997, 619, 'Pink');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Ellwood McAllaster', '89.50', 'Dodge', 'Aspen', 1976, 539, 'Blue');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Janeczka Hedan', '70.52', 'BMW', 'X6', 2013, 877, 'Fuscia');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Kirsti Ivers', '55.54', 'Nissan', 'Pathfinder', 2003, 151, 'Fuscia');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Judon Farady', '72.39', 'BMW', 'M3', 2012, 278, 'Puce');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Clayborne Easen', '42.50', 'Volkswagen', 'Golf', 1987, 412, 'Red');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Gabriel Cheevers', '66.27', 'Jaguar', 'X-Type', 2002, 779, 'Fuscia');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Lowrance Paradine', '87.33', 'Cadillac', 'Escalade EXT', 2009, 179, 'Violet');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Ronda Grinov', '49.06', 'Mazda', 'RX-7', 1990, 964, 'Fuscia');
insert into avtopark (haydovchi, daromad, moshina_nomi, model, moshin_yili, mashina_raqami, moshina_rangi) values ('Tandy De Vries', '73.07', 'Saturn', 'S-Series', 1996, 484, 'Blue');
